'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Skills', [
      { name: 'HTML/CSS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'JQuery', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Angular', createdAt: new Date(), updatedAt: new Date() },
      { name: 'TypeScript', createdAt: new Date(), updatedAt: new Date() },
      { name: 'SCSS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'LESS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Webpack', createdAt: new Date(), updatedAt: new Date() },
      { name: 'NodeJS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Express', createdAt: new Date(), updatedAt: new Date() },
      { name: 'React', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Redux', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Vue', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Django', createdAt: new Date(), updatedAt: new Date() },
      { name: 'PHP', createdAt: new Date(), updatedAt: new Date() },
      { name: 'MSSQL', createdAt: new Date(), updatedAt: new Date() },
      { name: 'MySQL', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Postgres', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Mongo', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Sequelize', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Mongoose', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Eloquent', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Redis', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Laravel', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Gulp', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Grunt', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Elixir', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Git', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Linting', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Ruby', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Rails', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Perl', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Python', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Bash/Command Line Scripting', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Responsive Design', createdAt: new Date(), updatedAt: new Date() },
      { name: 'UX', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Slack', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Machine Learning', createdAt: new Date(), updatedAt: new Date() },
      { name: 'AI', createdAt: new Date(), updatedAt: new Date() },
      { name: 'ARKit', createdAt: new Date(), updatedAt: new Date() },
      { name: 'E2E QA', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Unit Testing / QA', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Nix Server Management', createdAt: new Date(), updatedAt: new Date() },
      { name: 'AWS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Kentico', createdAt: new Date(), updatedAt: new Date() },
      { name: 'C#', createdAt: new Date(), updatedAt: new Date() },
      { name: '.NET', createdAt: new Date(), updatedAt: new Date() },
      { name: 'CakePHP', createdAt: new Date(), updatedAt: new Date() },
      { name: 'CMS', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Swift', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Java', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Kotlin', createdAt: new Date(), updatedAt: new Date() },
      { name: 'VirtualBox', createdAt: new Date(), updatedAt: new Date() },
      { name: 'Vagrant', createdAt: new Date(), updatedAt: new Date() },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Users', null, {});
  }
};
